# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0003_remove_task_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time_tracking.Project'),
        ),
    ]
