# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0003_profile'),
        ('time_tracking', '0004_task_project'),
    ]

    operations = [
    ]
