# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0005_merge_20161118_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracking.Project'),
        ),
    ]
